export interface Testimonial {
  id: string;
  author: string;
  location?: string;
  rating: number;
  date: string;
  body: string;
  category: "first-time-buyer" | "seller" | "luxury" | "relocation" | "move-up" | "general";
  featured?: boolean;
}

// Real Google reviews — verified from GBP April 2026
// Note: some reviewers spelled Chelsey's name as "Chelsea" — kept verbatim.
export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    author: "Haley Mindt",
    rating: 5,
    date: "2026-03-19",
    body: "As first-time homebuyers, we were honestly a little overwhelmed going into the process—but working with Chelsey made all the difference. She took the time to explain every step in a way that felt clear and manageable, and she was always there to answer our questions (no matter how small). She truly advocated for us and made sure we felt confident in every decision. Beyond that, she went above and beyond to make the experience not just smooth, but actually enjoyable. We're so grateful to have had her by our side and cannot recommend her enough!",
    category: "first-time-buyer",
    featured: true,
  },
  {
    id: "t2",
    author: "Tyler Shearer",
    location: "Coeur d'Alene, ID",
    rating: 5,
    date: "2026-03-19",
    body: "Chelsea delivered an exceptional experience on this luxury home purchase in Coeur d'Alene, Idaho. As a lender specializing in jumbo and high-end transactions, I can confidently say her level of communication and professionalism is elite. She was outstanding not only in working with our lending team, but also in guiding her client through every step of the process. In luxury real estate, details matter—and Chelsea stayed proactive, organized, and ahead of every milestone, allowing us to structure and close this jumbo loan smoothly and ahead of schedule. What stood out most was the experience she created. Her client walked away with everything they envisioned in their home purchase, which is exactly what you want in a high-end transaction.",
    category: "luxury",
    featured: true,
  },
  {
    id: "t3",
    author: "Tabbetha Sonn",
    rating: 5,
    date: "2025-11-13",
    body: "Chelsey has been absolutely incredible. We found the home ourselves, but she's the one who made everything possible. She went above and beyond in every way, truly treating our situation like her own family would be living here. I had a million questions, a ton of stress, and I definitely over-communicated… she never once seemed bothered. She explained everything, checked in constantly, and kept us grounded through one of the biggest decisions of our lives. She even helped us get connected with an amazing lender, which made everything smoother. And honestly? She doesn't feel like \"just\" a realtor anymore… she feels like a friend. If you want someone who genuinely cares, works hard, and supports you every step of the way, Chelsey is the one. We're so grateful for her.",
    category: "general",
    featured: true,
  },
  {
    id: "t4",
    author: "Erin Dornburgh",
    rating: 5,
    date: "2026-02-26",
    body: "If there is anyone to help with buying a home, look no further, Chelsey Fanning is the best! Very diligent, knowledgeable and makes the process as smooth as possible for all involved. Would use her services again and highly recommend.",
    category: "general",
  },
  {
    id: "t5",
    author: "Amanda S",
    rating: 5,
    date: "2026-02-19",
    body: "We had an amazing buying experience with Chelsey! She is very timely and responsive, we never had to wait long to hear from her about a question we had. She is very professional and organized. She met us for our first round of showings with a binder of printed listings that we were set to see that day. We ended up having to purchase our bare land site-unseen while living out of state and she made the experience seamless! She made sure all the documents got to us and all the to-do's were checked off before purchasing. She went above and beyond for us in our unique situation!",
    category: "relocation",
  },
  {
    id: "t6",
    author: "Emily Bohn",
    rating: 5,
    date: "2026-02-12",
    body: "I could not recommend Chelsey enough. She truly dedicates her time to her clients and will not stop until they get what they want! A dedicated, genuine, and local expert. 10/10",
    category: "general",
  },
  {
    id: "t7",
    author: "Jennifer Lund",
    rating: 5,
    date: "2026-02-12",
    body: "Chelsea was truly exceptional from start to finish. We couldn't have asked for a better guide through the home buying process. She was knowledgeable, responsive, and incredibly patient, taking the time to explain every step and make sure we felt confident in our decisions. When we ran into a few difficult and stressful situations along the way, Chelsea handled them with professionalism, and care, always advocating for our best interests. Her attention to detail and commitment to us as clients never wavered, and it made all the difference. We are so grateful for her support and expertise and would wholeheartedly recommend Chelsea to anyone looking for a realtor they can truly trust.",
    category: "first-time-buyer",
  },
  {
    id: "t8",
    author: "Katie LaMothe",
    rating: 5,
    date: "2026-01-29",
    body: "Chelsey was and is the absolute best realtor in town!! She is kind and caring and helped me and my husband with buying our first house! I was soooo nervous about everything but she calmed me down and answered every single question we had and more! It was a flawless process with her and I can not wait to use her in the future! She's the best!!!",
    category: "first-time-buyer",
  },
  {
    id: "t9",
    author: "Mike Melnick",
    rating: 5,
    date: "2026-01-22",
    body: "Chelsey is a great listener, always responds to questions immediately, she was on top of every aspect of both purchasing and selling our house. Highly recommend.",
    category: "seller",
  },
  {
    id: "t10",
    author: "Chance Johnson",
    rating: 5,
    date: "2026-01-22",
    body: "Chelsey was an absolute pleasure to work with in attaining our home. Knowledgeable, honest and sincere, she made the process painless as well as effortless on our end. I recommend using Chelsey to everyone I know!",
    category: "general",
  },
  {
    id: "t11",
    author: "Andrea Broenneke",
    rating: 5,
    date: "2025-12-04",
    body: "Chelsey went above and beyond to help us find the right house and then she negotiated on our behalf for terms that worked for us. She is a true professional, great at communicating and always ready to help when we needed it. Best experience I've ever had with a realtor!! Thank you!",
    category: "general",
  },
  {
    id: "t12",
    author: "Elizabeth Bowling",
    rating: 5,
    date: "2025-12-04",
    body: "Chelsea is knowledgeable, quick with communication, excellent at working towards my specific needs and goals for house sale, and a gem in negotiations and clear communication. Highly recommend!",
    category: "seller",
  },
  {
    id: "t13",
    author: "Jessica Kohler",
    rating: 5,
    date: "2025-12-04",
    body: "Chelsey made my home buying experience such a breeze. She goes above and beyond for her clients. She even had a welcome home gift basket for me when I signed on my home. She is wonderful and I highly recommend her!",
    category: "general",
  },
  {
    id: "t14",
    author: "Emily Anderson",
    rating: 5,
    date: "2025-11-20",
    body: "Amazing!!! Chelsey is so knowledgeable and her attention to detail is top notch!!! Would definitely use and recommend her to everyone!",
    category: "general",
  },
  {
    id: "t15",
    author: "Kris Smith",
    rating: 5,
    date: "2025-11-13",
    body: "I have known and worked with Chelsey for almost 10 years and in that time she helped my husband and I with the sale of our home, worked diligently to assist in the possible purchase of other homes and properties for our family and has also facilitated the sale of my mother's home. Having worked in real estate myself for many years, I know the people and I know how difficult it can be to make it in this very competitive business - you have work hard to stand out, be dedicated, and truly care about what you do. Former Realtors are not always the easiest clients to have but I can assure you, we know the business and we know who to trust, so rest assured when I say that Chelsey Fanning knows what she's doing and will work hard for you and your family too.",
    category: "seller",
  },
  {
    id: "t16",
    author: "Allie Guiry",
    rating: 5,
    date: "2025-11-13",
    body: "Chelsey is the best hands down! I could not recommend her enough! She was so helpful and answered all our questions no matter the day! Thank you for making the process so smooth!",
    category: "general",
  },
  {
    id: "t17",
    author: "Robert Reynolds",
    rating: 5,
    date: "2025-11-13",
    body: "Chelsey was fantastic in our home purchase, managing a cross-country purchase for us seamlessly. Very professional, courteous and communicative. She also helped find service providers for various house-related things, as we had no idea who to call in the area. She was a pleasure to work with.",
    category: "relocation",
  },
  {
    id: "t18",
    author: "Jamie Davis",
    rating: 5,
    date: "2025-11-13",
    body: "We have known Chelsey Fanning since 2018, and in that time she has helped us to find and purchase two beautiful homes in the Coeur d'Alene/ Hayden area. These finds did not come quickly as we were looking for very specific things in a home; that being said, Chelsey was always patient and never did we ever feel like we were being pressured to buy. She listened to our criteria and guided us to homes that she thought would work for us. Chelsey was always accessible to answer our real estate questions, and if she did not have the answer immediately, she researched it and found the answer. While working with Chelsey, you can tell that she loves what she does. We would recommend Chelsey to others… she is a great realtor and now a friend!",
    category: "move-up",
  },
  {
    id: "t19",
    author: "David Burnett",
    rating: 5,
    date: "2025-11-13",
    body: "Chelsea was amazing when we bought our house and made it very comfortable for us. She was great again when we sold our house with her couple of years later.",
    category: "seller",
  },
  {
    id: "t20",
    author: "Marissa",
    rating: 5,
    date: "2025-11-13",
    body: "Highly recommend! Chelsey was so great to work with. She was professional, friendly, always quick to respond and answered absolutely any questions we had. She went above and beyond to help us find our new family home! We'll be using her again for sure.",
    category: "general",
  },
  {
    id: "t21",
    author: "Austin Garrett",
    rating: 5,
    date: "2025-11-13",
    body: "I had an amazing experience working with Chelsey. From start to finish, she was professional, responsive, and truly attentive to our needs. She made the home buying, and selling, process smooth and stress-free, offering valuable insights and expert advice. Her negotiation skills were top-notch, we were pleased with how much she was able to sell our home for, and the deal she negotiated on our purchase. If you're looking for a reliable, knowledgeable realtor, I highly recommend Chelsey!",
    category: "seller",
  },
  {
    id: "t22",
    author: "Kimberly Miller",
    rating: 5,
    date: "2025-11-13",
    body: "I've worked with Chelsey on several listings, and she's fantastic to work with. She's organized, professional, and her communication is always spot on, she keeps everything running smoothly and makes my job easier. On a more personal note, She also sold my mom's home for her and did an outstanding job with that. Chelsey truly looks out for her clients and makes the process as stress free as possible. She goes above and beyond. I highly recommend her to anyone looking for a Realtor who's dependable, communicative, fun and great at what she does.",
    category: "seller",
  },
  {
    id: "t23",
    author: "Jessie Mitchell",
    rating: 5,
    date: "2025-11-13",
    body: "I had the pleasure of working with Chelsey when inquiring on my first home. She had the poise, professionalism, confidence and knowledge to keep my comfort in check and provide me with the perfect opportunity. Would recommend her to anyone anytime!",
    category: "first-time-buyer",
  },
  {
    id: "t24",
    author: "Nichole Gerhardt",
    rating: 5,
    date: "2025-11-13",
    body: "Chelsey exemplifies the highest standards of professionalism, integrity, and dedication in real estate. Throughout the entire process, she demonstrates exceptional reliability, a strong work ethic, and an unwavering commitment to doing what is right for her clients. Her honesty and transparency fosters complete trust, and her attention to detail ensures every step is handled with precision and care. Dependable from start to finish, Chelsey consistently goes above and beyond to deliver outstanding results. Her steadfast commitment and ethical approach sets her apart in an industry where those qualities truly matter. I highly recommend Chelsey to anyone seeking a trustworthy, hardworking, and principled real estate professional.",
    category: "general",
  },
  {
    id: "t25",
    author: "Desiree Jones",
    rating: 5,
    date: "2025-11-06",
    body: "I had the pleasure of working with Chelsey Fanning on a recent transaction, and she was absolutely phenomenal to collaborate with. Chelsey is the definition of professional, detail-oriented, and on the ball. She stays ahead of every deadline and ensures all the moving parts of a deal come together seamlessly. Her communication is beyond exceptional!! She is always quick to respond, clear, and proactive. It made the entire process smooth and stress-free for everyone involved. Chelsey's organization and follow-through reflect true professionalism and care for her clients. If you're looking to work with an agent in North Idaho who is sharp, responsive, and genuinely invested in delivering an outstanding experience, Chelsey is one of the best in the business!!",
    category: "general",
  },
  {
    id: "t26",
    author: "Danny Rodriguez",
    rating: 5,
    date: "2025-11-06",
    body: "If you're looking for an ethical, hard charging, pro-active Realtor in North Idaho; then look no further than Chelsey Fanning. Chelsey Fanning helped me find the property to build my dream home on, in 2020. Chelsey made sure everything was clearly understood at every step of the process. Chelsey is experienced with residential and commercial real estate.",
    category: "general",
  },
];
